---
title: "r-matricies"
author: "mish"
format: html
editor_options: 
  chunk_output_type: console
---

## Creating Matricies in R 

```{r}
my_values <- seq(from = 1, to = 10, by = 1)

# Look at it ----
my_values

# Convert to matrix ----
my_matrix <- matrix(data=my_values, nrow = 2, ncol = 5, byrow = TRUE)

# Look at it and check class ----
my_matrix
class(my_matrix)
```

## Incorrectly declared matrix sizes

```{r}
matrix(data = my_values, nrow =2, ncol=3, byrow = TRUE)
matrix(data = my_values, nrow =3, ncol=4, byrow = TRUE)
```

## Let's do some math with matricies

```{r}
# Scalar multiplication ----
4 * my_matrix

# Create a second matrix ----
my_values2 <- seq(from=21, to=30, by=1)
my_values2
my_matrix2 <- matrix(data=my_values2, nrow=2, byrow = TRUE)
my_matrix2

# add matrices ----
my_matrix + my_matrix2

# sub matrices ----
my_matrix2 - my_matrix

# multiplying matrices ----
my_matrix * my_matrix2

```

```{r}
# make a couple of 2x2 matrices ----
cats <- matrix(data = c(0,4,3,1), nrow=2, byrow = TRUE)
cats
dogs <- matrix(data = c(6,-3,0,2), nrow = 2, byrow = TRUE)

# take dot product ----
cats %*% dogs
```

## Leslie Matrix Example

```{r}
# Create the matrix ----
insect_leslie <- matrix(data=c(0,0,600,0.2,0,0,0,0.08,0), nrow = 3, ncol=3, byrow=TRUE)
insect_leslie

# Specify initial condition ----
# Insect life stage populations (year 0) ----
insect_y0 <- c(12000, 700, 500)

# pop y1 ----
insect_y1 <- insect_leslie %*% insect_y0
insect_y1

# pop y2 ----
insect_y2 <- insect_leslie %*% insect_y1
insect_y2

# pop y3 ----

insect_y3 <- insect_leslie %*% insect_y2
insect_y3

```

# Another Leslie Matrix Example
```{r}
# create the matrix ----
tree_leslie <- matrix(data = c(0,0,5000,0.1,0,0,0,0.06,0.95), nrow = 3, byrow = TRUE)
tree_leslie
# initial condition ----
tree_0 <- c(5000, 0, 0)
# year 1
tree_1 <- tree_leslie %*% tree_0
tree_1
# year 2
tree_2 <- tree_leslie %*% tree_1
tree_2
# year 3
tree_3 <- tree_leslie %*% tree_2
tree_3
# year 4
tree_4 <- tree_leslie %*% tree_3
tree_4
```

